name: Prisma Cloud – CI/CD Runs
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  prisma:
    runs-on: ubuntu-latest
    environment: Prisma-Cloud        # <-- required if BC_API_KEY is an Environment secret
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run Prisma Cloud
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@v12.1968.0   # pin instead of "master"
        env:
          PRISMA_API_URL: https://api.sg.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          # soft_fail: true   # optional
