name: Prisma Cloud Code Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prisma-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download twistcli
        run: |
          TOKEN=$(curl -s -k -u "${{ secrets.PRISMA_ACCESS_KEY }}:${{ secrets.PRISMA_SECRET_KEY }}" \
            "${{ secrets.PRISMA_CONSOLE_URL }}/login" | jq -r .token)

          curl -k -H "authorization: Bearer $TOKEN" \
            "${{ secrets.PRISMA_CONSOLE_URL }}/api/v1/util/twistcli" -o twistcli
          chmod +x twistcli

      - name: Run Prisma Cloud Code Scan
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}"
          ./twistcli coderepo scan \
            --address ${{ secrets.PRISMA_CONSOLE_URL }} \
            --token $TOKEN \
            --repo-id "github/${{ github.repository }}" \
            --branch "$BRANCH" \
            --commit "${{ github.sha }}"
