name: Prisma Cloud Code Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prisma-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download twistcli
        run: |
          curl -k -L "${{secrets.PRISMA_CONSOLE_URL}}/api/v1/util/twistcli" -o twistcli
          chmod +x twistcli

      - name: Run twistcli scan
        run: |
          ./twistcli coderepo scan \
            --address "${{secrets.PRISMA_CONSOLE_URL}}" \
            --user "${{secrets.PRISMA_ACCESS_KEY}}" \
            --password "${{secrets.PRISMA_SECRET_KEY}}" \
            --repo-id "github/${{github.repository}}" \
            --branch "${{github.ref_name}}" \
            --commit "${{github.sha}}"

